### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by opgbaudouin** [contensis/contensis-management-api#12]
Upgraded from the last RC to 1.0.1

ReferenceError: window is not defined
    at new Client (D:\active\contensisapi\node_modules\contensis-management-api\lib\client\client.js:26:32)
    at Function.create (D:\active\contensisapi\node_modules\contensis-management-api\lib\client\client.js:44:16)

Running server side, node: v12.16.3
  "contensis-core-api": "1.0.1",
   "contensis-management-api": "1.0.1",
   "contensis-delivery-api": "1.1.5",

 Update should be a typeof windows === 'undefined' check there, otherwise breaks server side.

**Comment by opgbaudouin** [comment]
You can bypass the error by creating the managementClient in the a new format:

ManagementClient.create(config, fetch);

If the second parameter is filled it's OK as the !!window check does not occur. However still an issue as the config type also has the fetchFn option.

**Comment by alexpop-zengenti** [comment]
Hi,
If you instantiating the client in a Node.js environment (server side) you need to use a UniversalClient instance or a NodeJsClient instance. You can use this Express example:
https://github.com/contensis/contensis-management-api-examples/blob/main/express-test-app/app.js

Hope this helps :)

**Comment by opgbaudouin** [comment]
Indeed - thank you Alex!

For reference to others:

import {UniversalClient as ManagementClient} from "contensis-management-api/lib/client/";  //Mixing Delivery and Management API in backend work

No longer need to set any fetch, neither in the config or the createCall as the updated library polyfills the fetch itself now.
